# Generated by Django 5.0 on 2024-10-15 04:32

import FutureStarAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'futurestar_app_album',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fields_images/')),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=500)),
                ('additional_information', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'futurestar_app_field',
            },
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'futurestar_app_followrequest',
            },
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type', models.IntegerField(choices=[(1, 'Images'), (2, 'Videos')], default=1)),
                ('media_file', models.FileField(blank=True, null=True, upload_to=FutureStarAPI.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'futurestar_app_gallary',
            },
        ),
        migrations.CreateModel(
            name='OTPSave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('OTP', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'futurestar_app_otpsave',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'futurestar_app_post',
            },
        ),
        migrations.CreateModel(
            name='Post_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'futurestar_app_post_comment',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('team_establishment_date', models.DateField(blank=True, null=True)),
                ('team_president', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('age_group', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_fees', models.CharField(blank=True, max_length=255, null=True)),
                ('branches', models.CharField(blank=True, max_length=500, null=True)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='team/team_logo/')),
                ('team_background_image', models.ImageField(blank=True, null=True, upload_to='team/team_background_image/')),
                ('team_uniform', models.ImageField(blank=True, null=True, upload_to='team/team_uniform/')),
            ],
            options={
                'db_table': 'futurestar_app_team',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_starting_date', models.DateField(blank=True, null=True)),
                ('tournament_final_date', models.DateField(blank=True, null=True)),
                ('number_of_team', models.CharField(blank=True, max_length=255, null=True)),
                ('tournament_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age_group', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tournament_logo/')),
                ('tournament_joining_cost', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'futurestar_app_tournament',
            },
        ),
    ]
