# Generated by Django 4.2.11 on 2024-10-08 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FutureStar_App', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fields_images/')),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=500)),
                ('additional_information', models.TextField(blank=True, max_length=255, null=True)),
                ('field_capacity', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.fieldcapacity')),
                ('ground_type', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.groundmaterial')),
                ('user_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'futurestar_app_field',
            },
        ),
        migrations.CreateModel(
            name='OTPSave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('OTP', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'futurestar_app_registration_otpsave',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'futurestar_app_post',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_starting_date', models.DateField(blank=True, null=True)),
                ('tournament_final_date', models.DateField(blank=True, null=True)),
                ('number_of_team', models.CharField(blank=True, max_length=255, null=True)),
                ('tournament_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age_group', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tournament_logo/')),
                ('tournament_joining_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('tournament_fields', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.field')),
                ('user_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'futurestar_app_tournament',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('team_establishment_date', models.DateField(blank=True, null=True)),
                ('team_president', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('age_group', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_fees', models.CharField(blank=True, max_length=255, null=True)),
                ('branches', models.CharField(blank=True, max_length=500, null=True)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='team/team_logo/')),
                ('team_background_image', models.ImageField(blank=True, null=True, upload_to='team/team_background_image/')),
                ('team_uniform', models.ImageField(blank=True, null=True, upload_to='team/team_uniform/')),
                ('team_type', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.category')),
                ('user_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'futurestar_app_team',
            },
        ),
        migrations.CreateModel(
            name='Post_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='FutureStarAPI.post_comment')),
                ('post', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='FutureStarAPI.post')),
                ('team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.team')),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'futurestar_app_post_comment',
            },
        ),
    ]
