# Generated by Django 5.0 on 2024-12-24 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FutureStarAPI', '0001_initial'),
        ('FutureStar_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.eventtype'),
        ),
        migrations.AddField(
            model_name='event_comment',
            name='event',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to='FutureStarAPI.event'),
        ),
        migrations.AddField(
            model_name='event_comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_replies', to='FutureStarAPI.event_comment'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.event'),
        ),
        migrations.AddField(
            model_name='eventlike',
            name='event',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_likes', to='FutureStarAPI.event'),
        ),
        migrations.AddField(
            model_name='field',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.city'),
        ),
        migrations.AddField(
            model_name='field',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FutureStar_App.country'),
        ),
        migrations.AddField(
            model_name='field',
            name='field_capacity',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.fieldcapacity'),
        ),
        migrations.AddField(
            model_name='field',
            name='ground_type',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.groundmaterial'),
        ),
        migrations.AddField(
            model_name='field',
            name='user_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('created_by_id', 'creator_type', 'target_id', 'target_type')},
        ),
        migrations.AddField(
            model_name='gallary',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_set', to='FutureStarAPI.album'),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='FutureStarAPI.post_comment'),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='FutureStarAPI.post'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='FutureStarAPI.post'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.post'),
        ),
        migrations.AddField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='FutureStarAPI.post'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.report'),
        ),
        migrations.AddField(
            model_name='team',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.city'),
        ),
        migrations.AddField(
            model_name='team',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FutureStar_App.country'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='founder_of_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='team_type',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.category'),
        ),
        migrations.AddField(
            model_name='teambranch',
            name='age_group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.agegroup'),
        ),
        migrations.AddField(
            model_name='teambranch',
            name='field_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.fieldcapacity'),
        ),
        migrations.AddField(
            model_name='teambranch',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.usergender'),
        ),
        migrations.AddField(
            model_name='teambranch',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.team'),
        ),
        migrations.AddField(
            model_name='teamuniform',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.team'),
        ),
        migrations.AddField(
            model_name='traininggroups',
            name='group_founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_founder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eventlike',
            unique_together={('creator_type', 'created_by_id', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('created_by_id', 'creator_type', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together={('created_by_id', 'creator_type', 'post')},
        ),
    ]
