# Generated by Django 5.0 on 2024-09-30 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='parent',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='FutureStarAPI.post_comment'),
        ),
    ]
