# Generated by Django 5.0 on 2024-10-07 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FutureStarAPI', '0001_initial'),
        ('FutureStar_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_capacity',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.fieldcapacity'),
        ),
        migrations.AddField(
            model_name='field',
            name='ground_type',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.groundmaterial'),
        ),
        migrations.AddField(
            model_name='field',
            name='user_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='FutureStarAPI.post_comment'),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='post',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='FutureStarAPI.post'),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='team_type',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.category'),
        ),
        migrations.AddField(
            model_name='team',
            name='user_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_fields',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.field'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='user_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
