# Generated by Django 4.2.11 on 2024-10-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpsave',
            name='device_token',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='otpsave',
            name='device_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='otpsave',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterModelTable(
            name='otpsave',
            table='futurestar_app_otpsave',
        ),
    ]
