# Generated by Django 5.0 on 2024-10-22 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FutureStarAPI', '0001_initial'),
        ('FutureStar_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_album', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='field',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.city'),
        ),
        migrations.AddField(
            model_name='field',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FutureStar_App.country'),
        ),
        migrations.AddField(
            model_name='field',
            name='field_capacity',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.fieldcapacity'),
        ),
        migrations.AddField(
            model_name='field',
            name='ground_type',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.groundmaterial'),
        ),
        migrations.AddField(
            model_name='field',
            name='user_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gallary',
            name='album_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallary_set', to='FutureStarAPI.album'),
        ),
        migrations.AddField(
            model_name='gallary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gallary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='FutureStarAPI.post_comment'),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='post',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='FutureStarAPI.post'),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='FutureStarAPI.post'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='FutureStarAPI.post'),
        ),
        migrations.AddField(
            model_name='postview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.city'),
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FutureStar_App.country'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_type',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.category'),
        ),
        migrations.AddField(
            model_name='team',
            name='user_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.team'),
        ),
        migrations.AddField(
            model_name='post',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.team'),
        ),
        migrations.AddField(
            model_name='gallary',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.team'),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='from_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_follow_requests_sent', to='FutureStarAPI.team'),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='to_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_follow_requests_received', to='FutureStarAPI.team'),
        ),
        migrations.AddField(
            model_name='album',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.city'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FutureStar_App.country'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_fields',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.field'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='user_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traininggroups',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.city'),
        ),
        migrations.AddField(
            model_name='traininggroups',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FutureStar_App.country'),
        ),
        migrations.AddField(
            model_name='traininggroups',
            name='user_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.traininggroups'),
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.traininggroups'),
        ),
        migrations.AddField(
            model_name='gallary',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_group_gallary', to='FutureStarAPI.traininggroups'),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='from_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_follow_requests_sent', to='FutureStarAPI.traininggroups'),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='to_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_follow_requests_received', to='FutureStarAPI.traininggroups'),
        ),
        migrations.AddField(
            model_name='album',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_group_album', to='FutureStarAPI.traininggroups'),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('from_group', 'to_group'), ('from_team', 'to_team'), ('from_user', 'to_user')},
        ),
    ]
