# Generated by Django 5.0 on 2024-10-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='followrequest',
            table='futurestar_app_followrequest',
        ),
    ]
