# Generated by Django 5.0 on 2024-10-15 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0002_initial'),
        ('FutureStar_App', '0003_rename_coach_certificates_user_coach_certificate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('group_username', models.CharField(blank=True, max_length=255, null=True)),
                ('group_type', models.IntegerField(choices=[(1, 'Open'), (2, 'Close')], default=1)),
                ('bio', models.TextField(blank=True, null=True)),
                ('group_president', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('group_logo', models.ImageField(blank=True, null=True, upload_to='group/group_logo/')),
                ('group_background_image', models.ImageField(blank=True, null=True, upload_to='group/group_background_image/')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FutureStar_App.country')),
                ('user_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'futurestar_app_traininggroups',
            },
        ),
    ]
