# Generated by Django 5.0 on 2024-10-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0003_otpsave'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpsave',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
