# Generated by Django 5.0 on 2024-09-30 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0004_post_image'),
        ('FutureStar_App', '0021_cms_pages_achivement_heading_ar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fields_images/')),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=500)),
                ('additional_information', models.TextField(max_length=255)),
                ('field_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.fieldcapacity')),
                ('ground_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.groundmaterial')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'futurestar_app_field',
            },
        ),
    ]
