# Generated by Django 5.0 on 2024-10-15 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0004_field_latitude_field_longitude_team_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='album_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallary_set', to='FutureStarAPI.album'),
        ),
    ]
