# Generated by Django 5.1.1 on 2024-10-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0004_otpsave_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpsave',
            name='device_token',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='otpsave',
            name='device_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
