# Generated by Django 5.1.1 on 2024-10-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0005_otpsave_device_token_otpsave_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpsave',
            name='device_token',
        ),
        migrations.RemoveField(
            model_name='otpsave',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='otpsave',
            name='email',
        ),
        migrations.RemoveField(
            model_name='otpsave',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='otpsave',
            name='password',
        ),
        migrations.RemoveField(
            model_name='otpsave',
            name='type',
        ),
        migrations.RemoveField(
            model_name='otpsave',
            name='username',
        ),
        migrations.AlterField(
            model_name='otpsave',
            name='OTP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otpsave',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
