# Generated by Django 5.0 on 2024-09-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0005_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='additional_information',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
