# Generated by Django 5.0 on 2024-10-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0005_alter_gallary_album_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='album_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallary_set', to='FutureStarAPI.album'),
        ),
    ]
