# Generated by Django 5.0 on 2024-10-15 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0006_alter_gallary_album_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.traininggroups'),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='gropu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.traininggroups'),
        ),
    ]
