# Generated by Django 5.0 on 2024-10-11 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0006_remove_otpsave_device_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.team'),
        ),
    ]
