# Generated by Django 5.0 on 2024-10-01 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0007_tournament'),
        ('FutureStar_App', '0022_cms_home_dynamic_achivements_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('team_establishment_date', models.DateField(blank=True, null=True)),
                ('team_president', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('age_group', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_fees', models.CharField(blank=True, max_length=255, null=True)),
                ('branches', models.CharField(blank=True, max_length=500, null=True)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='team/team_logo/')),
                ('team_background_image', models.ImageField(blank=True, null=True, upload_to='team/team_background_image/')),
                ('team_uniform', models.ImageField(blank=True, null=True, upload_to='team/team_uniform/')),
                ('team_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'futurestar_app_team',
            },
        ),
    ]
