# Generated by Django 5.0 on 2024-10-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0007_post_group_post_comment_gropu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='traininggroups',
            name='group_type',
        ),
    ]
