# Generated by Django 5.0 on 2024-10-17 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0008_remove_followrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_group_album', to='FutureStarAPI.traininggroups'),
        ),
        migrations.AddField(
            model_name='gallary',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_group_gallary', to='FutureStarAPI.traininggroups'),
        ),
    ]
