# Generated by Django 5.0 on 2024-10-02 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0008_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_comment',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.team'),
        ),
    ]
