# Generated by Django 5.0 on 2024-10-17 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0009_album_group_id_gallary_group_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequest',
            name='from_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_follow_requests_sent', to='FutureStarAPI.traininggroups'),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='from_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_follow_requests_sent', to='FutureStarAPI.team'),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='to_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_follow_requests_received', to='FutureStarAPI.traininggroups'),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='to_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_follow_requests_received', to='FutureStarAPI.team'),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
