# Generated by Django 5.0 on 2024-10-17 11:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0010_followrequest_from_group_followrequest_from_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('from_group', 'to_group'), ('from_team', 'to_team'), ('from_user', 'to_user')},
        ),
    ]
