# Generated by Django 5.0 on 2024-10-03 06:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0011_remove_state_country_delete_city_delete_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, help_text='0 = InActive | 1 = Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FutureStarAPI.country')),
            ],
            options={
                'db_table': 'futurestar_app_city',
            },
        ),
    ]
