# Generated by Django 5.0 on 2024-10-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0012_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
