# Generated by Django 5.0 on 2024-10-22 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStarAPI', '0013_post_address_post_city_post_country_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_comment',
            old_name='gropu_id',
            new_name='group_id',
        ),
    ]
