# Generated by Django 5.0 on 2024-10-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cms_advertise_partnership_dynamic_field',
            table='futurestar_app_cms_advertise_partnership_dynamic_field',
        ),
    ]
