# Generated by Django 5.0 on 2024-10-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cms_advertise_ads_dynamic_field',
            table='futurestar_app_cms_advertise_ads_dynamic_field',
        ),
        migrations.AlterModelTable(
            name='cms_advertise_partnership_dynamic_field',
            table='futurestar_app_cms_advertise_Partnership_dynamic_field',
        ),
        migrations.AlterModelTable(
            name='cms_advertise_premium_dynamic_field',
            table='futurestar_app_cms_advertise_premium_dynamic_field',
        ),
        migrations.AlterModelTable(
            name='cms_advertise_section_2_dynamic_field',
            table='futurestar_app_cms_advertise_section_2_dynamic_field',
        ),
        migrations.AlterModelTable(
            name='cms_home_dynamic_achivements_field',
            table='futurestar_app_cms_home_achivements_dynamic_field',
        ),
        migrations.AlterModelTable(
            name='cms_home_dynamic_field',
            table='futurestar_app_cms_home_dynamic_field',
        ),
    ]
