# Generated by Django 5.0 on 2024-09-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0002_cms_dicovery_dynamic_view'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='futurestar_app_news',
        ),
    ]
