# Generated by Django 5.0 on 2024-10-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0002_alter_cms_advertise_ads_dynamic_field_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms_pages',
            name='section_3_titlee_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cms_pages',
            name='section_3_titlee_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cms_pages',
            name='section_4_title_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cms_pages',
            name='section_4_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='cms_dicovery_dynamic_image',
            table='futurestar_app_cms_dicovery_dynamic_image',
        ),
    ]
