# Generated by Django 4.2.11 on 2024-09-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0002_cms_dicovery_dynamic_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='cms_dicovery_dynamic_image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(blank=True, null=True, upload_to='cmspages/')),
            ],
        ),
    ]
