# Generated by Django 4.2.11 on 2024-09-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0002_cms_pages_delete_contactpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_pages',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
