# Generated by Django 5.0 on 2024-10-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0002_remove_user_coach_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='coach_certificates',
            new_name='coach_certificate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='referee_certificates',
            new_name='referee_certificate',
        ),
    ]
