# Generated by Django 5.0 on 2024-10-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0003_alter_cms_pages_section_3_titlee_ar_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cms_dicovery_dynamic_view',
            table='futurestar_app_cms_dicovery_dynamic_view',
        ),
    ]
