# Generated by Django 5.0 on 2024-09-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0003_alter_news_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='app_feature',
            table='futurestar_app_app_feature',
        ),
        migrations.AlterModelTable(
            name='category',
            table='futurestar_app_category',
        ),
        migrations.AlterModelTable(
            name='cms_dicovery_dynamic_view',
            table='futurestar_app_cms_dicovery_dynamic_view',
        ),
        migrations.AlterModelTable(
            name='cms_pages',
            table='futurestar_app_cms_pages',
        ),
        migrations.AlterModelTable(
            name='eventtype',
            table='futurestar_app_eventtype',
        ),
        migrations.AlterModelTable(
            name='fieldcapacity',
            table='futurestar_app_fieldcapacity',
        ),
        migrations.AlterModelTable(
            name='global_clients',
            table='futurestar_app_global_clients',
        ),
        migrations.AlterModelTable(
            name='groundmaterial',
            table='futurestar_app_groundmaterial',
        ),
        migrations.AlterModelTable(
            name='inquire',
            table='futurestar_app_inquire',
        ),
        migrations.AlterModelTable(
            name='partners',
            table='futurestar_app_partners',
        ),
        migrations.AlterModelTable(
            name='player_profile',
            table='futurestar_app_player_profile',
        ),
        migrations.AlterModelTable(
            name='role',
            table='futurestar_app_role',
        ),
        migrations.AlterModelTable(
            name='slider_content',
            table='futurestar_app_slider_content',
        ),
        migrations.AlterModelTable(
            name='systemsettings',
            table='futurestar_app_systemsettings',
        ),
        migrations.AlterModelTable(
            name='team_members',
            table='futurestar_app_team_members',
        ),
        migrations.AlterModelTable(
            name='testimonial',
            table='futurestar_app_testimonial',
        ),
        migrations.AlterModelTable(
            name='tournamentstyle',
            table='futurestar_app_tournamentstyle',
        ),
        migrations.AlterModelTable(
            name='tryout_club',
            table='futurestar_app_tryout_club',
        ),
        migrations.AlterModelTable(
            name='user',
            table='futurestar_app_user',
        ),
        migrations.AlterModelTable(
            name='usergender',
            table='futurestar_app_gender',
        ),
    ]
