# Generated by Django 4.2.11 on 2024-09-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0003_cms_pages_name_ar_cms_pages_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms_pages',
            name='sub_section_2_title_2_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cms_pages',
            name='sub_section_2_title_2_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
