# Generated by Django 4.2.11 on 2024-09-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0003_cms_dicovery_dynamic_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cms_advertise_dynamic_field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='cmspages/')),
            ],
            options={
                'db_table': 'futureStar_app_advertise_dynamic_field',
            },
        ),
    ]
