# Generated by Django 5.0 on 2024-09-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0004_rename_sub_title_app_feature_sub_title_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsettings',
            old_name='youtube',
            new_name='pinterest',
        ),
    ]
