# Generated by Django 4.2.11 on 2024-09-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0004_alter_cms_pages_sub_section_2_title_2_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_pages',
            name='meta_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
