# Generated by Django 4.2.11 on 2024-09-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0004_cms_advertise_dynamic_field'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cms_advertise_dynamic_field',
            table='futureStar_app_cms_advertise_dynamic_field',
        ),
    ]
