# Generated by Django 4.2.11 on 2024-09-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0005_cms_pages_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_pages',
            name='meta_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cms_pages',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
