# Generated by Django 4.2.11 on 2024-09-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0005_alter_cms_advertise_dynamic_field_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_pages',
            name='section_2_country_name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_2_country_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
