# Generated by Django 5.0 on 2024-09-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0005_rename_youtube_systemsettings_pinterest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsettings',
            old_name='snapchat',
            new_name='twitter',
        ),
    ]
