# Generated by Django 4.2.11 on 2024-09-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0006_cms_pages_meta_content_alter_cms_pages_meta_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cms_pages',
            old_name='meta_content',
            new_name='meta_content_ar',
        ),
        migrations.RenameField(
            model_name='cms_pages',
            old_name='meta_title',
            new_name='meta_title_ar',
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='meta_content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
