# Generated by Django 4.2.11 on 2024-09-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0006_cms_pages_section_2_country_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms_pages',
            name='section_2_logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
