# Generated by Django 5.0 on 2024-09-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0004_alter_app_feature_table_alter_category_table_and_more'),
        ('FutureStar_App', '0007_alter_cms_pages_section_2_logo'),
    ]

    operations = [
    ]
