# Generated by Django 5.0 on 2024-09-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0008_merge_20240923_1408'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cms_dicovery_dynamic_view',
            table=None,
        ),
    ]
