# Generated by Django 4.2.11 on 2024-09-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0009_alter_cms_dicovery_dynamic_view_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_pages',
            name='heading_year_title_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='heading_year_title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
