# Generated by Django 5.0 on 2024-09-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0014_user_device_token_user_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
