# Generated by Django 4.2.11 on 2024-09-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0015_alter_user_device_token_alter_user_device_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cms_home_dynamic_field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('content_ar', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='cmspages/')),
            ],
            options={
                'db_table': 'futureStar_app_cms_home_dynamic_field',
            },
        ),
    ]
