# Generated by Django 5.0 on 2024-09-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0017_user_age_user_bio_user_city_user_contry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contry',
            new_name='country',
        ),
    ]
