# Generated by Django 5.0 on 2024-09-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0018_rename_contry_user_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='main_playing_possition',
            new_name='main_playing_position',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='secondary_playing_possition',
            new_name='secondary_playing_position',
        ),
    ]
