# Generated by Django 5.0 on 2024-09-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0019_rename_main_playing_possition_user_main_playing_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_pages',
            name='section_10_heading_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_10_heading_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_10_title_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_10_title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_2_background',
            field=models.ImageField(blank=True, null=True, upload_to='cmspages/'),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_4_background',
            field=models.ImageField(blank=True, null=True, upload_to='cmspages/'),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='sub_heading_name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='sub_heading_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cms_pages',
            name='section_2_logo',
            field=models.ImageField(blank=True, null=True, upload_to='cmspages/'),
        ),
    ]
