# Generated by Django 5.0 on 2024-09-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0020_cms_pages_section_10_heading_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_pages',
            name='achivement_heading_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='achivement_heading_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='achivement_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='achivement_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
