# Generated by Django 5.0 on 2024-10-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0021_cms_pages_achivement_heading_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cms_home_dynamic_achivements_field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_id', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_en', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'futureStar_app_cms_home_achivements_dynamic_field',
            },
        ),
    ]
