# Generated by Django 4.2.11 on 2024-10-01 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0022_cms_home_dynamic_achivements_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquire',
        ),
    ]
