# Generated by Django 4.2.11 on 2024-10-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0023_delete_inquire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'futurestar_app_inquire',
            },
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_3_titlee_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_3_titlee_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cms_pages',
            name='section_2_images',
            field=models.ImageField(blank=True, null=True, upload_to='cmspages/'),
        ),
    ]
