# Generated by Django 4.2.11 on 2024-10-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0024_inquire_cms_pages_section_3_titlee_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_pages',
            name='section_6_content_ar_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_6_content_ar_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_6_content_ar_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_6_content_ar_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_6_content_ar_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_6_content_ar_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_6_content_en_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_6_content_en_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_6_content_en_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_6_content_en_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_6_content_en_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_6_content_en_6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
