# Generated by Django 4.2.11 on 2024-10-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0025_cms_pages_section_6_content_ar_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_pages',
            name='section_6_image',
            field=models.ImageField(blank=True, null=True, upload_to='cmspages/'),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_6_logo',
            field=models.ImageField(blank=True, null=True, upload_to='cmspages/'),
        ),
    ]
