# Generated by Django 4.2.11 on 2024-10-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0026_cms_pages_section_6_image_cms_pages_section_6_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_pages',
            name='section_9_image',
            field=models.ImageField(blank=True, null=True, upload_to='cmspages/'),
        ),
    ]
