# Generated by Django 4.2.11 on 2024-10-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0027_cms_pages_section_9_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_dicovery_dynamic_image',
            name='field_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
