# Generated by Django 5.0 on 2024-10-02 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0027_cms_pages_section_9_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergender',
            name='name',
        ),
        migrations.AddField(
            model_name='usergender',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usergender',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.usergender'),
        ),
    ]
