# Generated by Django 4.2.11 on 2024-10-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0028_cms_dicovery_dynamic_image_field_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cms_dicovery_dynamic_view',
            old_name='content',
            new_name='content_ar',
        ),
        migrations.RenameField(
            model_name='cms_dicovery_dynamic_view',
            old_name='title',
            new_name='title_ar',
        ),
        migrations.AddField(
            model_name='cms_dicovery_dynamic_view',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_dicovery_dynamic_view',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
