# Generated by Django 4.2.11 on 2024-10-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0029_rename_content_cms_dicovery_dynamic_view_content_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_dicovery_dynamic_view',
            name='field_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
