# Generated by Django 4.2.11 on 2024-10-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0030_cms_dicovery_dynamic_view_field_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_pages',
            name='section_3_sub_content_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_3_sub_content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_3_sub_title_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_3_sub_title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
