# Generated by Django 4.2.11 on 2024-10-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0031_cms_pages_section_3_sub_content_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cms_pages',
            name='section_3_image',
        ),
    ]
