# Generated by Django 4.2.11 on 2024-10-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0032_remove_cms_pages_section_3_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_pages',
            name='section_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='cmspages/'),
        ),
    ]
