# Generated by Django 4.2.11 on 2024-10-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0028_remove_usergender_name_usergender_name_ar_and_more'),
        ('FutureStar_App', '0033_cms_pages_section_3_image'),
    ]

    operations = [
    ]
