# Generated by Django 4.2.11 on 2024-10-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0034_merge_20241003_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergender',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='usergender',
            name='name_en',
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_2_discover_title_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_pages',
            name='section_2_discover_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergender',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cms_pages',
            name='sub_section_2_title_1_ar',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='cms_pages',
            name='sub_section_2_title_1_en',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
