# Generated by Django 5.0 on 2024-10-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0035_city_country_alter_user_city_city_country_and_more'),
        ('FutureStar_App', '0035_remove_usergender_name_ar_remove_usergender_name_en_and_more'),
    ]

    operations = [
    ]
