# Generated by Django 4.2.11 on 2024-10-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0036_merge_20241003_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergender',
            name='name',
        ),
        migrations.AddField(
            model_name='usergender',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usergender',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cms_pages',
            name='sub_section_2_title_1_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cms_pages',
            name='sub_section_2_title_1_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.usergender'),
        ),
    ]
