# Generated by Django 4.2.11 on 2024-10-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0036_merge_20241003_1808'),
        ('FutureStar_App', '0037_remove_usergender_name_usergender_name_ar_and_more'),
    ]

    operations = [
    ]
