# Generated by Django 4.2.11 on 2024-10-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0038_merge_20241004_0525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cms_advertise_dynamic_field',
            new_name='cms_advertise_section_2_dynamic_field',
        ),
    ]
