# Generated by Django 4.2.11 on 2024-10-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0039_rename_cms_advertise_dynamic_field_cms_advertise_section_2_dynamic_field'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cms_advertise_section_2_dynamic_field',
            table='futureStar_app_cms_advertise_section_2_dynamic_field',
        ),
    ]
