# Generated by Django 4.2.11 on 2024-10-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0040_alter_cms_advertise_section_2_dynamic_field_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_advertise_section_2_dynamic_field',
            name='field_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
