# Generated by Django 4.2.11 on 2024-10-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0041_cms_advertise_section_2_dynamic_field_field_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cms_advertise_section_2_dynamic_field',
            old_name='content',
            new_name='content_ar',
        ),
        migrations.RenameField(
            model_name='cms_advertise_section_2_dynamic_field',
            old_name='title',
            new_name='title_ar',
        ),
        migrations.AddField(
            model_name='cms_advertise_section_2_dynamic_field',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cms_advertise_section_2_dynamic_field',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
